#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "claughinghouse"
email = "claughinghouse@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519_githubSigningKey.pub"

[remotes.origin]
auto-track-bookmarks = "*"

[git.lfs]
enabled = true
