

import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

  [font.normal]
  family = "IntoneMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "IntoneMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "IntoneMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "IntoneMono Nerd Font"
  style = "Bold Italic"

