

import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
     "~/.config/alacritty/dracula-pro-alucard.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13

  [font.normal]
  family = "IntoneMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "IntoneMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "IntoneMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "IntoneMono Nerd Font"
  style = "Bold Italic"

[window]
decorations = "full"
dynamic_padding = false

  [window.dimensions]
  columns = 80
  lines = 24

  [window.padding]
  x = 0
  y = 0
